config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :productos
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :productos, only: [:index,:create,:show]
      devise_scope :user do
      
      match '/sessions' => 'sessions#create', via: :post
      match '/sessions' => 'sessions#destroy', via: :delete
      end
      
    
        match '/productos' => 'productos#create', via: :post
        match '/productos' => 'productos#destroy', via: :delete
      
        
    end
  end
  devise_scope :user do
  
  authenticated :user do
    root to: 'page#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'devise/sessions#new', as: :unauthenticated_root
  end
end
  #root to: redirect ('devise/sessions#new')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  before_action :current_user

  require 'json_web_token'
  def authenticate!
    auth_header= request.header['Authorization']
    token     =auth_header.split(' ').last
    return true if JsonWebToken.decode(token)
  rescue
    render json: {error: "Error en la autenticacion,Token Errado"}
  end 
  
    def invalid_authentication
        render json: { error: t('device.failure.unauthentication') }, status: :unauthorized
       
    end
    private
    def current_user
      puts("***********")
      ingreso =decode_http[:id]

           
      @user ||= User.find(ingreso) 
      
      @current_user=ingreso
      puts(@current_user)
    end
    def decode_http
      auth_header= request.headers['Authorization']
      token=auth_header.split(' ').last
      JsonWebToken.decode(token)
    end
end

app/controllers/api/v1/productos_controller.rb
class Api::V1::ProductosController < Api::V1::BaseController
    require 'json_web_token'
    respond_to :json
    skip_before_action :verify_authenticity_token   
    
   def index
    @productos= Producto.order('id');
    json_response={
      producto: @productos
    }
    respond_with json_response, callback:params[:callback]
    

   end   
    def create
       
      producto = Producto.new(productos_params)       
      producto.user_id = @current_user
      if producto.save
        render json: {status: 'SUCCES', message:'producto', data:producto},status: :ok 
      else
        render json: {status: 'ERROR', message:'Producto no almacenado',data:producto.errors},status: :unprocessable_entity
      end
     end
     def show
      @productos=Producto.find(params[:id])
       #@producto = EcoProducto.find(params[:id])
     end
     private
     def productos_params
       params.require(:producto).permit(:nombre,:descripcion,:estado)
     end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Devise::SessionsController
    require 'json_web_token'
    skip_before_action :verify_authenticity_token
    def create
        user =User.find_for_database_authentication(email: params[:user][:email])
        if user && user.valid_password?(params[:user][:password])
            auth_token = jwt_token(user)
            render json: {auth_token: auth_token}
        else
            invalid_login
        end
        
    end
    def destroy
        #todo crear accion de logout 
        
    end
    def jwt_token(user)
        JsonWebToken.encode({id: user.id, email: user.email})
    end

    private
    def invalid_login
        render json: { error: t('device.failure.not_found_in_database') }, status: :unauthorized
    end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
    def index
        @user=User.all        
    end
    def show
        @user = User.find(params[:id])
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  
    def new
      
      
        @producto = Producto.new
      
     end
    
     def create

      
       
       @producto = Producto.new(productos_params)       
       @producto.user_id = current_user.id
       
       if @producto.save
        redirect_to new_producto_path
      else
        render :new
      end
     end
   
     def index
      @productos=Producto.all
     end

     def show
      @productos=Producto.find(params[:id])
       #@producto = EcoProducto.find(params[:id])
     end
   
     private
     def productos_params
       params.require(:producto).permit(:nombre,:descripcion,:estado)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/producto_helper.rb
module ProductoHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoEcoRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>    
nav ul li a{
  color: black;
}    
</style>
  </head>
  

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/page/_parcial.html.erb
esto es un parcial

<ul>
<li>esto es una lista</li>
</ul>

app/views/page/index.html.erb
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Document</title>
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/bootstrap.min.css">


</head>
<div>
<nav class="navbar navbar-expand-lg" >
	<a class="navbar-brand letraNav" href="#">Menú</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		<div class="navbar-nav">
			<a class="nav-item nav-link letraNav" href="#">Categorias</a>
			<a class="nav-item nav-link letraNav" href="productos/new">Productos</a>
			<a class="nav-item nav-link letraNav" href="#">Sugerencias</a>
			<a class="nav-item nav-link disabled letraNav" href="#">Registrarse</a>
		</div>
	</div>
</nav>
</div>


<body>
<div class="container">
<div class="row">
<div class="col_sm_12">

	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="carousel-item active" >
				<%= image_tag("amarillo.jpg", :alt =>"First slide", :class =>"img-responsive" ) %>
				 <div class="carousel-caption">
				 <h6>organico</h6>
				 </div>
			 </div>
			 <div class="carousel-item">
			   <%= image_tag("azul.jpg", :alt =>"Second slide", :class =>"img_rounded") %>

			 </div>
			<div class="carousel-item">
				<%= image_tag("gris.jpg", :alt =>"Second slide") %>
		
			</div>
			<div class="carousel-item">
				<%= image_tag("cont_organico.jpg", :alt =>"Second slide") %>

			</div>
			
		</div>
		<!-- control -->
		<a class="left carousel-control" href="#carouselExampleIndicators" role="button" data-slide="prev">
		<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#my-first-carousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right"></span>
		</a>
		
	</div>

</div>
</div>

</div>

<script type="text/javascript" src="js/script.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
	crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
	crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
	crossorigin="anonymous"></script>
	</body> 

	<div >
 <p>Fedesoft 2018, EcoCapital INC  All Rights Reserved.</p>
 </div>

app/views/productos/_form.html.erb
<div class="container">
Usuario:<%= current_user.id %>
<%= form_for @producto do |f| %>
    <div class="form-group">
    <%= f.label :nombre, :for=>"nameField" %><br>
    <%= f.text_field :nombre, :class=>"form-control", :id=>"nameField",placeholder: "Ingrese Nombre del Producto" %>
    </div>
    <div class="form-group">
    <%= f.label :descripcion, :for=>"descField" %><br>
    <%= f.text_field :descripcion, :class=>"form-control", :id=>"descField" ,placeholder: "Ingrese Descripción del producto" %>
    </div>
    <div class="form-group">
    <%= f.label :estado, :for=>"estField" %><br>
    <%= f.text_field :estado, :class=>"form-control", :id=>"estField" ,placeholder: "Estado" %>
    </div>
       
    <ul class="list-inline">
<%= f.submit 'Create', :class=>"btn btn-success" %>
<%= button_tag "Reset", type: :reset, :class=>"btn btn-default" %>

</ul>
    
 <% end %>   
 </div>

app/views/productos/_regresar.html.erb
<%= button_to 'Regresar', productos_path, method: :get %>

app/views/productos/edit.html.erb
<h1> Actualizar producto </h1>

<%= render 'form' %>

app/views/productos/index.html.erb
<div class="container">
<h3> Listado de Producto </h3>
<div class="form-group">
<section class="search-results">
<header>
<h4 class="h3">Results</h4>
</header>
<ol class="list-group">
<% @productos.each do |producto| %>
<li class="list-group-item">
<div class="form-group">
<label for="codigoprd">Codigo producto:</label>
 <%= producto.id %>
 <label for="cnomprd">Nombre producto:</label>
 <%= producto.nombre %>
 <label for="descprd">Descripción producto:</label>
<%= producto.descripcion %>
</div>
Joined <%= l producto.created_at.to_date %>
</li>
<% end %>
</ol>
</section
</div>
</div>

app/views/productos/new.html.erb
<div class="container">
<h4>Formulario de producto</h4>
<%= render 'form' %>
</div>

app/views/productos/show.html.erb
<h1> Consulta del prodcuto </h1>

Id_Producto: <%= @productos.nombre %> <br>
Descripcion: <%= @productos.descripcion %>

<%= render 'regresar' %>